
export const SET_PRODUCT ={
    SET_CATEGORIES:"SET_CATEGORIES",
    SET_CATEGORIES_START: "SET_CATEGORIES_START",
    SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",
    SET_CATEGORIES_ERROR: "SET_CATEGORIES_ERROR"
}